import Link from 'next/link'
import Navbar from '@/components/shared/Navbar'
import Footer from '@/components/shared/Footer'

export default function PrivacyPage() {
  return (
    <>
      <Navbar />
      <main className="mx-auto max-w-3xl px-4 py-16">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Privacy Policy</h1>
        <p className="text-sm text-gray-400 mb-10">Last updated: June 2026</p>

        <div className="prose prose-gray max-w-none text-sm leading-relaxed space-y-6">
          <section>
            <h2 className="text-lg font-semibold text-gray-800 mb-2">1. What We Collect</h2>
            <p className="text-gray-600">We collect your name, email address, and Google account identifiers when you sign up. During interview sessions, we temporarily process your voice recordings to produce transcripts. We also collect session data (questions, transcripts, scores) to provide feedback and track your progress.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-800 mb-2">2. How We Use Your Data</h2>
            <p className="text-gray-600">Your data is used solely to: provide the mock interview service, generate AI feedback, improve our question and feedback quality (in aggregate, never linked to you personally), and send transactional emails (e.g. payment receipts).</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-800 mb-2">3. Data Sharing</h2>
            <p className="text-gray-600">We share data with: Supabase (database & storage), Anthropic (AI feedback generation — audio transcripts are sent as text), Deepgram (speech-to-text — audio is sent for transcription only), and Razorpay (payment processing). We do not sell your data to third parties.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-800 mb-2">4. Audio Data</h2>
            <p className="text-gray-600">Voice recordings are uploaded to secure Supabase storage. Transcripts generated by Deepgram are stored with your session. Audio files are retained for 90 days and then automatically deleted.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-800 mb-2">5. Your Rights</h2>
            <p className="text-gray-600">You may request deletion of your account and all associated data at any time by emailing <a href="mailto:support@careersetu.in" className="text-indigo-600 hover:underline">support@careersetu.in</a>. We will process deletion within 30 days.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-800 mb-2">6. Cookies</h2>
            <p className="text-gray-600">We use session cookies for authentication (via Supabase Auth). No third-party advertising or tracking cookies are used.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-800 mb-2">7. Security</h2>
            <p className="text-gray-600">All data is encrypted in transit (HTTPS) and at rest. Row-level security policies ensure users can only access their own data.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-800 mb-2">8. Contact</h2>
            <p className="text-gray-600">For privacy concerns, email <a href="mailto:support@careersetu.in" className="text-indigo-600 hover:underline">support@careersetu.in</a>.</p>
          </section>
        </div>

        <div className="mt-10 pt-8 border-t border-gray-200">
          <Link href="/" className="text-sm text-indigo-600 hover:underline">← Back to home</Link>
        </div>
      </main>
      <Footer />
    </>
  )
}
