import type { Metadata } from 'next'
import Link from 'next/link'
import Navbar from '@/components/shared/Navbar'
import Footer from '@/components/shared/Footer'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'CareerSetu terms of service — your rights and obligations when using our AI mock interview platform.',
  alternates: { canonical: '/terms' },
  robots: { index: true, follow: false },
}

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="mx-auto max-w-3xl px-4 py-16">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-10">Last updated: June 2026</p>

        <div className="prose prose-gray max-w-none text-sm leading-relaxed space-y-6">
          <section>
            <h2 className="text-lg font-semibold text-gray-800 mb-2">1. Acceptance of Terms</h2>
            <p className="text-gray-600">By accessing or using CareerSetu (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Service.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-800 mb-2">2. Description of Service</h2>
            <p className="text-gray-600">CareerSetu provides AI-powered mock interview practice sessions, voice recording and transcription, and structured feedback reports. The Service is intended for personal interview preparation use only.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-800 mb-2">3. User Accounts</h2>
            <p className="text-gray-600">You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You must be at least 13 years old to use the Service.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-800 mb-2">4. Payments and Subscriptions</h2>
            <p className="text-gray-600">Paid plans are billed monthly. You may cancel at any time; access continues until the end of the current billing period. All payments are processed securely by Razorpay. We do not store your payment card details.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-800 mb-2">5. Acceptable Use</h2>
            <p className="text-gray-600">You agree not to misuse the Service, attempt to reverse-engineer our AI systems, use the Service for any unlawful purpose, or interfere with other users&apos; access.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-800 mb-2">6. Intellectual Property</h2>
            <p className="text-gray-600">All content generated by CareerSetu&apos;s AI systems remains the property of CareerSetu. Your voice recordings and transcripts belong to you and are stored securely. You grant us a limited licence to process them solely to provide the Service.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-800 mb-2">7. Limitation of Liability</h2>
            <p className="text-gray-600">CareerSetu is provided &ldquo;as is&rdquo;. We do not guarantee interview success or employment outcomes. Our liability is limited to the amount you paid us in the 3 months prior to any claim.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-800 mb-2">8. Changes to Terms</h2>
            <p className="text-gray-600">We may update these terms from time to time. Continued use of the Service after changes constitutes acceptance of the new terms.</p>
          </section>
          <section>
            <h2 className="text-lg font-semibold text-gray-800 mb-2">9. Contact</h2>
            <p className="text-gray-600">Questions? Email us at <a href="mailto:support@careersetu.in" className="text-indigo-600 hover:underline">support@careersetu.in</a>.</p>
          </section>
        </div>

        <div className="mt-10 pt-8 border-t border-gray-200">
          <Link href="/" className="text-sm text-indigo-600 hover:underline">← Back to home</Link>
        </div>
      </main>
      <Footer />
    </>
  )
}
